### ISSUE TITLE
License

### ISSUE THREAD

**Issue by evur** [BeamMP/BeamNG-FuelStations#4]
It would be good to add a license to this project so that anyone can contribute. I think that the MPL 2.0 would be suited.

**Comment by Starystars67** [comment]
Hey there, thank you for your input and interest :)

Thanks for pointing this out. Spending a little time looking over them I think GPL 3.0 will do the job nicely.
Open to your input and opinion on it first before I put it in though.

Thanks

**Comment by evur** [comment]
Thanks for replying!

I would still recommend using the MPL as it fits the project better. Besides that, there are some really bad controversies around the creator of the license and the FSF.

**Comment by Starystars67** [comment]
Fair enough. For now I am happy for this license to be used.
I will apply it now.

**Comment by Starystars67** [comment]
License has now been applied. 
I will close this issue for now but if there is anything else please feel free to reopen or raise a new one.

Thanks again for your help!

**Comment by evur** [comment]
@Starystars67 You can execute the following Git commands to reduce the commits to one:
```sh
git reset --soft HEAD~3
git commit -m "Added license"
git push --force
```

**Comment by Starystars67** [comment]
Thank you, that should be it now.
